name: Docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        run: |
          docker build . -t ric3

      - name: test docker image
        run: |
          docker run -v ./examples/counter.aig:/model.aig ric3 model.aig || [ $? -eq 10 ]
